name = "EmeraldData"
uuid = "8231cf5e-2e2a-4221-b520-6690d15c76c2"
authors = ["Yujie Wang", "Hao Jiang"]
version = "1.0.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
NetcdfIO = "6a36f34d-89cf-423a-87c4-84549e82f670"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DataFrames = "1.8.0"
DocStringExtensions = "0.8.5, 0.9.0"
HTTP = "0.9.14, 1.0.5"
JSON = "1.2.0"
NetcdfIO = "0.2.6"
ProgressMeter = "1.7.1"
YAML = "0.4.12"
julia = "1.10"
