name = "EmeraldData"
uuid = "2bb7d46c-a1fe-4c81-b098-5748a6633b16"
version = "1.0.0"
authors = ["Yujie Wang", "Emily Gu", "Hao Jiang"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NetcdfIO = "6a36f34d-89cf-423a-87c4-84549e82f670"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[sources]
PkgUtility = {rev = "wyujie", url = "https://github.com/Yujie-W/PkgUtility.jl.git"}

[compat]
Genie = "5.33.18"
HTTP = "0.9.14, 1.0.5"
JSON = "1.2.0"
NetcdfIO = "0.2.6"
PkgUtility = "0.3.1"
YAML = "0.4.12"
julia = "1.10"
